import = [
    # "~/.config/alacritty/themes/github-dark.toml",
    # "~/.config/alacritty/themes/nord.toml",
    "~/.config/alacritty/themes/tokyonight-storm.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 2, y = 2 }
# startup_mode = "Fullscreen"
startup_mode = "Windowed"
option_as_alt = "Both"

[scrolling]
history = 99999

[selection]
save_to_clipboard = true

[shell]
program= "zsh"
args=[ "-l", "-c", "tmux attach || tmux" ]

[font]
size = 11

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[keyboard]
bindings = [
    { key = "Enter", mods = "Shift|Control", action = "ToggleFullscreen" },

    { key = "Right", mods = "Alt", chars = "\u001BF" }, # Skip word forward
    { key = "Left", mods = "Alt", chars = "\u001BB" },  # Skip word backward
    { key = "Back", mods = "Alt", chars = "\u0017" },   # Delete word backward

    { key = "Back", mods = "Shift", chars = "\u0015" }, # Delete line

    { key = "V", mods = "Shift|Control", action = "Paste" },
    { key = "C", mods = "Shift|Control", action = "Copy" },

    { key = "=", mods = "Control", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
]
