# Wire tc alias to the teamcity completion function generated by 'tc completion zsh'
compdef _teamcity tc

# TeamCity CLI fzf completion
# Trigger: tc <cmd> <subcmd> **<TAB>  or  tc ... --flag **<TAB>
#
# fzf calls _fzf_complete_tc with the full left buffer as ONE string ($1),
# e.g. "tc run start ". Use ${(z)1} to split into words.

_fzf_complete_tc() {
  local -a words=(${(z)1})
  local -a o=(--height 50% --border --ansi)
  local last="${words[-1]}" sub="${words[2]}" act="${words[3]}"

  # Flag value completions — detect by last word before **
  case "$last" in
    --project|-p)
      if [[ "$1" =~ ' agent ' ]]; then
        _fzf_complete "${o[@]}" -- "$@" < <(tc pool list --json | jq -r '.pool[].name')
      else
        _fzf_complete "${o[@]}" -- "$@" < <(tc project list -n 9999 --json | jq -r '.project[].id')
      fi; return ;;
    --job|-j)
      _fzf_complete "${o[@]}" -- "$@" < <(tc job list -n 9999 --json | jq -r '.buildType[].id')
      return ;;
    --agent)
      _fzf_complete "${o[@]}" -- "$@" < <(
        tc agent list -n 9999 --json | jq -r '.agent[] | "\(.id)\t\(.name)"')
      return ;;
    --pool)
      _fzf_complete "${o[@]}" -- "$@" < <(tc pool list --json | jq -r '.pool[].name')
      return ;;
    --branch|-b)
      _fzf_complete "${o[@]}" -- "$@" < <(git branch --format='%(refname:short)' 2>/dev/null)
      return ;;
    --status)
      _fzf_complete "${o[@]}" -- "$@" < <(printf '%s\n' success failure running error unknown)
      return ;;
    --revision)
      _fzf_complete "${o[@]}" -- "$@" < <(git log --oneline -50 2>/dev/null | awk '{print $1}')
      return ;;
  esac

  # Count positionals already typed after "tc sub act" (skip flag+value pairs)
  local pos=0 skip_next=0
  for a in "${words[4,-1]}"; do
    if (( skip_next )); then skip_next=0; continue; fi
    case "$a" in
      --project|--job|--agent|--pool|--branch|--revision|\
      --status|--user|--comment|--since|--until|-p|-j|-b|-u|-m)
        skip_next=1 ;;
      -*) ;;
      *) (( pos++ )) ;;
    esac
  done

  # Positional completions
  case "$sub" in
    run)
      case "$act" in
        start)
          _fzf_complete "${o[@]}" -- "$@" < <(tc job list -n 9999 --json | jq -r '.buildType[].id') ;;
        cancel|restart|pin|unpin|tag|untag|view|log|watch|artifacts|download|changes|comment|tests)
          _fzf_complete "${o[@]}" -- "$@" < <(
            tc run list -n 9999 --json | jq -r '.build[] | "\(.id)\t\(.buildType.name // .buildTypeId)"') ;;
      esac ;;
    job)
      case "$act" in
        view|pause|resume|tree|param)
          _fzf_complete "${o[@]}" -- "$@" < <(tc job list -n 9999 --json | jq -r '.buildType[].id') ;;
      esac ;;
    project)
      case "$act" in
        view|param|settings|token)
          _fzf_complete "${o[@]}" -- "$@" < <(tc project list -n 9999 --json | jq -r '.project[].id') ;;
      esac ;;
    agent)
      case "$act" in
        view|enable|disable|authorize|deauthorize|reboot|exec|term|jobs)
          _fzf_complete "${o[@]}" -- "$@" < <(tc agent list -n 9999 --json | jq -r '.agent[].name') ;;
        move)
          if (( pos == 0 )); then
            _fzf_complete "${o[@]}" -- "$@" < <(tc agent list -n 9999 --json | jq -r '.agent[].name')
          else
            _fzf_complete "${o[@]}" -- "$@" < <(tc pool list --json | jq -r '.pool[].name')
          fi ;;
      esac ;;
    queue)
      case "$act" in
        approve|remove|top)
          _fzf_complete "${o[@]}" -- "$@" < <(
            tc queue list -n 9999 --json | jq -r '.build[] | "\(.id)\t\(.buildType.name // .buildTypeId)"') ;;
      esac ;;
    pool)
      case "$act" in
        view)
          _fzf_complete "${o[@]}" -- "$@" < <(tc pool list --json | jq -r '.pool[].name') ;;
        link|unlink)
          if (( pos == 0 )); then
            _fzf_complete "${o[@]}" -- "$@" < <(tc pool list --json | jq -r '.pool[].name')
          else
            _fzf_complete "${o[@]}" -- "$@" < <(tc project list -n 9999 --json | jq -r '.project[].id')
          fi ;;
      esac ;;
  esac
}

_fzf_complete_tc_post() { awk '{print $1}'; }
