---
- name: Get arch
  set_fact:
    lazysql_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'x86_64' }}"
    lazydocker_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'x86_64' }}"
    lazygit_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'x86_64' }}"
    go_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'amd64' }}"
    regolith_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'amd64' }}"
    fastfetch_arch: "{{ 'aarch64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Set timezone to Europe/Copenhagen
  become: true
  community.general.timezone:
    name: Europe/Copenhagen

- name: Update apt cache
  apt:
    update_cache: true
  become: true

- name: Install required packages
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - wget
      - curl
      - locales
    state: present
  become: true

- name: Add Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/unstable
  become: true

- name: Register the Regolith public key to local apt
  ansible.builtin.apt_key:
    url: https://regolith-desktop.org/regolith.key
    state: present
    keyring: /usr/share/keyrings/regolith-archive-keyring.gpg
  become: true

- name: Add the Regolith repository to apt sources
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ regolith_arch }}
      signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg]
      https://regolith-desktop.org/release-3_0-ubuntu-jammy-{{ regolith_arch }}
      jammy main
    filename: "regolith"
    state: present
  become: true

- name: Update apt cache again
  apt:
    update_cache: true
  become: true

- name: Install packages
  apt:
    name:
      - lua5.4
      - luarocks
      - zsh
      - i3
      - picom
      - regolith-desktop
      - regolith-session-flashback
      - regolith-look-lascaille
      - gnome-screenshot
      - i3lock-fancy
      - git
      - tmux
      - neovim
      - sudo
      - python3-neovim
      - python3-dev
      - python3-pip
      - python3-venv
      - fontconfig
      - unzip
      - fd-find
      - bat
      - exa
      - ncdu
      - tree
      - clang
      - cmake
      - build-essential
      - net-tools
      - traceroute
      - git-lfs
      - axel
      - sshfs
      - clangd
      - snapd
      - cargo
    state: present
  become: true

- name: Install i3-autolayout
  shell: cargo install --root /usr i3-autolayout
  become: true

- name: Install ripgrep
  shell: cargo install --root /usr --features 'pcre2' ripgrep
  become: true

- name: Install alacritty
  community.general.snap:
    name: alacritty
    classic: true
  become: true

- name: Install yq
  community.general.snap:
    name: yq
    classic: true
  become: true

- name: Install lazySQL
  include_role:
    name: common/lazysql
  vars:
    os: Linux
    arch: "{{ lazysql_arch }}"

- name: Install lazydocker
  include_role:
    name: common/lazydocker
  vars:
    os: Linux
    arch: "{{ lazydocker_arch }}"

- name: Install lazygit
  include_role:
    name: common/lazygit
  vars:
    os: Linux
    arch: "{{ lazygit_arch }}"

- name: Download the latest release of fastfetch
  get_url:
    url: "https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-{{fastfetch_arch}}.deb"
    dest: "/tmp/fastfetch.deb"

- name: Install fastfetch deb
  apt:
    deb: "/tmp/fastfetch.deb"
  become: true

- name: Download and install NVM
  include_role:
    name: common/nvm

- name: Install fzf
  include_role:
    name: common/fzf

- name: Create local bin directory
  file:
    path: ${HOME}/.local/bin
    state: directory

- name: Create symlink for fd
  file:
    src: /usr/bin/fdfind
    dest: ${HOME}/.local/bin/fd
    state: link

- name: Create symlink for python
  shell: >
    rm -f $(dirname $(which python3))/python &&
    ln -s $(which python3) $(dirname $(which python3))/python
  become: true

- name: Create symlink for tmux (Linux)
  file:
    src: /usr/bin/tmux
    dest: /usr/local/bin/tmux
    state: link
  become: true

- name: Create symlink for bat
  file:
    src: /usr/bin/batcat
    dest: ${HOME}/.local/bin/bat
    state: link

- name: Install go
  include_role:
    name: common/go
  vars:
    version: 1.23.0
    os: linux
    arch: "{{ go_arch }}"

- name: Generate locale
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: true

- name: Install oh-my-zsh
  include_role:
    name: common/oh-my-zsh

- name: Remove .tmux
  file:
    path: "${HOME}/.tmux"
    state: absent

- name: tpm
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

- name: Remove .config
  file:
    path: "${HOME}/.config"
    state: absent

- name: ensure fonts directory
  file:
    path: "${HOME}/.fonts"
    state: directory

- name: Copy font files on ubuntu
  copy:
    src: "../NerdFonts/"
    dest: "${HOME}/.fonts/"

- name: Refresh font cache
  shell: fc-cache -fv
  become: true

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "${HOME}/.config/"
  loop:
    - "../fzf"
    - "../nvim"
    - "../shell"
    - "../tmux"
    - "../alacritty"
    - "../fastfetch"
    - "../lazygit"
    - "../lazydocker"
    - "../regolith3"

- name: Make bar scripts executable
  file:
    path: "${HOME}/.config/regolith3/i3xrocks/scripts"
    recurse: true
    state: directory
    mode: "u+x"

- name: Make launch scripts executable
  file:
    path: "{{ item }}"
    mode: "u+x"
  loop:
    - "${HOME}/.config/alacritty/launch"
    - "${HOME}/.config/regolith3/picom/init"

- name: update-alternatives for alacritty
  community.general.alternatives:
    name: x-terminal-emulator
    path: "{{ ansible_env.HOME }}/.config/alacritty/launch"
    priority: 100
  become: true

- name: setup wallpaper for regolith
  blockinfile:
    path: "${HOME}/.config/regolith3/Xresources"
    block: |
      regolith.wallpaper.file: {{ ansible_env.HOME }}/.config/regolith3/desktop.jpeg
      regolith.lockscreen.wallpaper.file: {{ ansible_env.HOME }}/.config/regolith3/desktop.jpeg

- name: Add source commands to .zshrc
  blockinfile:
    path: "${HOME}/.zshrc"
    block: |
      source ${HOME}/.config/shell/aliases.zsh
      source ${HOME}/.config/shell/exports.zsh
      source ${HOME}/.config/shell/zsh.zsh
      source ${HOME}/.config/shell/p10k.zsh
      source ${HOME}/.config/shell/colors.zsh
      source ${HOME}/.config/fzf/completion.sh
      source ${HOME}/.config/fzf/keybindings.sh
      export PATH="$PATH:/usr/local/go/bin:$HOME/.local/bin"
      export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
    create: true

- name: Run tmux plugin install script
  command: ${HOME}/.tmux/plugins/tpm/scripts/install_plugins.sh

- name: Remove nvim cache
  file:
    path: "${HOME}/.cache/nvim"
    state: absent

- name: Remove nvim plugins
  file:
    path: "${HOME}/.local/share/nvim"
    state: absent

- name: Remove nvim logs
  file:
    path: "${HOME}/.local/state/nvim"
    state: absent

- name: Set default shell to zsh
  user:
    name: "{{ansible_env.USER}}"
    force: true
    shell: /bin/zsh
  become: true

# - name: Run nvim commands
#   environment:
#     PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
#     NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
#   shell: ". ${NVM_DIR}/nvm.sh && nvim --headless +TSUpdateSync +MasonToolsInstallSync +qa"
