---
- name: Get arch
  set_fact:
    lazysql_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'x86_64' }}"
    lazydocker_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'x86_64' }}"
    lazygit_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'x86_64' }}"
    go_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'amd64' }}"
    regolith_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'amd64' }}"
    docker_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'amd64' }}"
    fastfetch_arch: "{{ 'aarch64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Set timezone to Europe/Copenhagen
  become: true
  community.general.timezone:
    name: Europe/Copenhagen

- name: Update apt cache
  apt:
    update_cache: true
  become: true

- name: Install required packages
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - wget
      - curl
      - locales
    state: present
  become: true

- name: Add Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/unstable
  become: true

- name: Update apt cache again
  apt:
    update_cache: true
  become: true

- name: Install packages
  apt:
    name:
      - lua5.4
      - luarocks
      - zsh
      - git
      - tmux
      - neovim
      - sudo
      - python3-neovim
      - python3-dev
      - python3-pip
      - python3-venv
      - fontconfig
      - unzip
      - fd-find
      - bat
      - exa
      - ncdu
      - tree
      - clang
      - cmake
      - build-essential
      - net-tools
      - traceroute
      - git-lfs
      - axel
      - sshfs
      - clangd
      - snapd
      - cargo
    state: present
  become: true

- name: Install Docker
  include_role:
    name: common/linux/docker
  vars:
    arch: "{{ docker_arch }}"

- name: Install snap packages
  community.general.snap:
    name: alacritty
    classic: true
  loop:
    - alacritty
    - yq
    - slack
  become: true

- name: Install ripgrep
  include_role:
    name: common/shared/ripgrep


- name: Download and install NVM
  include_role:
    name: common/shared/nvm


- name: Create local bin directory
  file:
    path: ${HOME}/.local/bin
    state: directory

- name: Create symlink for fd
  file:
    src: /usr/bin/fdfind
    dest: ${HOME}/.local/bin/fd
    state: link

- name: Create symlink for python
  shell: >
    rm -f $(dirname $(which python3))/python &&
    ln -s $(which python3) $(dirname $(which python3))/python
  become: true

- name: Create symlink for tmux
  file:
    src: /usr/bin/tmux
    dest: /usr/local/bin/tmux
    state: link
  become: true

- name: Create symlink for bat
  file:
    src: /usr/bin/batcat
    dest: ${HOME}/.local/bin/bat
    state: link

- name: Install go
  include_role:
    name: common/shared/go
  vars:
    version: 1.23.0
    os: linux
    arch: "{{ go_arch }}"

- name: Generate locale
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: true

- name: Install oh-my-zsh
  include_role:
    name: common/shared/oh-my-zsh

- name: Setup Font
  include_role:
    name: common/linux/fonts
  vars:
    font_src: "{{playbook_dir}}/../NerdFonts/"

- name: Remove .config
  file:
    path: "${HOME}/.config"
    state: absent

- name: Create .config
  file:
    state: directory
    path: "${HOME}/.config"

- name: Setup zsh
  include_role:
    name: common/shared/zsh

- name: Install lazySQL
  include_role:
    name: common/shared/lazysql
  vars:
    os: Linux
    arch: "{{ lazysql_arch }}"

- name: Install lazydocker
  include_role:
    name: common/shared/lazydocker
  vars:
    os: Linux
    arch: "{{ lazydocker_arch }}"

- name: Install lazygit
  include_role:
    name: common/shared/lazygit
  vars:
    os: Linux
    arch: "{{ lazygit_arch }}"

- name: Install fastfetch
  include_role:
    name: common/linux/fastfetch
  vars:
    arch: "{{fastfetch_arch}}"

- name: Install fzf
  include_role:
    name: common/shared/fzf

- name: Setup tmux
  include_role:
    name: common/shared/tpm

- name: Setup nvim
  include_role:
    name: common/shared/nvim

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "${HOME}/.config/"
  loop:
    - "{{playbook_dir}}/../alacritty"
    - "{{playbook_dir}}/../fastfetch"
    
- name: Install Regolith
  include_role:
    name: common/linux/regolith
