---
- name: Download and install fnm
  shell: >
    curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "{{ansible_env.HOME}}/.fnm" --skip-shell --force-install

- name: Install Node.js
  shell: >
    $HOME/.fnm/fnm install --lts

- name: Append fnm commands to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - 'eval "$(fnm env)"'
    - "export PATH=$FNM_MULTISHELL_PATH:$PATH"

- name: Install neovim and tree-sitter
  shell: >
    $HOME/.fnm/fnm exec npm install -g neovim tree-sitter-cli
