---
- name: Install Lazysql
  become: true
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  shell: |
    /usr/local/go/bin/go install github.com/jorgerojas26/lazysql@latest

- name: Copy files
  copy:
    src: "{{playbook_dir}}/../lazysql"
    dest: "${HOME}/.config/"
