---
- name: Install Lazyjournal
  become: true
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_facts['env'].PATH }}"
  shell: |
    /usr/local/go/bin/go install github.com/Lifailon/lazyjournal@0.8.6
