---
version: "4.5.1"
arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or ansible_architecture == 'arm64' else 'amd64' }}"
install_url: "https://github.com/nroduit/Weasis/releases/download/v{{ version }}/weasis_{{ version }}-1_{{ arch }}.deb"
download_path: "/tmp/weasis_{{ arch }}.deb"
