---
- name: Copy files
  copy:
    src: "{{playbook_dir}}/../shell"
    dest: "${HOME}/.config/"

- name: Delete previous .zshrc
  file:
    path: ${HOME}/.zshrc
    state: absent

- name: Add source commands to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    insertafter: EOF
    create: true
  with_items:
    - "source ${HOME}/.config/shell/aliases.zsh"
    - "source ${HOME}/.config/shell/exports.zsh"
    - "source ${HOME}/.config/shell/zsh.zsh"
    - "source ${HOME}/.config/shell/p10k.zsh"
    - "source ${HOME}/.config/shell/colors.zsh"
    - "source ${HOME}/.config/fzf/completion.sh"
    - "source ${HOME}/.config/fzf/keybindings.sh"

- name: Set default shell to zsh
  user:
    name: "{{ansible_env.USER}}"
    force: true
    shell: /bin/zsh
  become: true
