---
- name: Copy files
  copy:
    src: "{{playbook_dir}}/../shell"
    dest: "${HOME}/.config/"

- name: Remove existing Zinit installation
  file:
    path: "{{ ansible_env.HOME }}/.zinit"
    state: absent

- name: Create Zinit directory
  file:
    path: "{{ ansible_env.HOME }}/.zinit/bin"
    state: directory
    mode: "0755"

- name: Clone Zinit repository
  git:
    repo: https://github.com/ryanstreur/zinit.git
    dest: "{{ ansible_env.HOME }}/.zinit/bin"
    depth: 1

- name: Ensure Zinit executable permissions
  file:
    path: "{{ ansible_env.HOME }}/.zinit/bin/zinit.zsh"
    mode: "0755"
    state: file

- name: Delete previous .zshrc
  file:
    path: ${HOME}/.zshrc
    state: absent

- name: Add source commands to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    insertafter: EOF
    create: true
  with_items:
    - "source ${HOME}/.config/shell/aliases.zsh"
    - "source ${HOME}/.config/shell/exports.zsh"
    - "source ${HOME}/.config/shell/p10k.zsh"
    - "source ${HOME}/.config/shell/colors.zsh"
    - "source ${HOME}/.config/shell/zinit.zsh"
    - "source ${HOME}/.config/shell/detect_system_style.zsh >/dev/null"

- name: set java_home for macOS
  when: ansible_os_family == "Darwin"
  shell: |
    sed -i '' 's|<JAVA_HOME_PATH>|/opt/homebrew/opt/openjdk@21|g' ${HOME}/.config/shell/exports.zsh

- name: set java_home for Linux
  when: ansible_os_family == "Debian"
  shell: |
    sed -i 's|<JAVA_HOME_PATH>|/usr/lib/jvm/java-21-openjdk-amd64|g' ${HOME}/.config/shell/exports.zsh

- name: Set default shell to zsh
  user:
    name: "{{ansible_env.USER}}"
    force: true
    shell: /bin/zsh
  become: true
