---
- name: Remove .oh-my-zsh
  file:
    path: "${HOME}/.oh-my-zsh"
    state: absent

- name: Install oh-my-zsh
  shell: >
    bash -c
    "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    ""
    --unattended

- name: Clone repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: 1
  loop:
    - {
      repo: "https://github.com/romkatv/powerlevel10k.git",
      dest: "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k",
    }
    - {
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git",
      dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting",
    }
    - {
      repo: "https://github.com/zsh-users/zsh-autosuggestions",
      dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions",
    }
    - {
      repo: "https://github.com/wfxr/forgit.git",
      dest: "${HOME}/.oh-my-zsh/custom/plugins/forgit",
    }
    - {
      repo: "https://github.com/fabrizioperria/zsh-venv-autoswitch.git",
      dest: "${HOME}/.oh-my-zsh/custom/plugins/autoswitch_virtualenv",
    }
    - {
      repo: "https://github.com/z-shell/zsh-eza.git",
      dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-eza",
    }
