---
- name: Download Weasis package
  get_url:
    url: "{{ install_url }}"
    dest: "{{ download_path }}"
    mode: '0644'
  register: download_result

- name: Install Weasis package
  apt:
    deb: "{{ download_path }}"
  when: download_result is succeeded
