---
- name: Set user home directory as a fact
  set_fact:
    user_home: "/home/{{ ansible_user_id }}"
    regolith_version: "3_2"

- name: Install required packages
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - wget
      - curl
      - locales
    state: present
  become: true

- name: Register the Regolith public key to local apt
  ansible.builtin.apt_key:
    url: https://regolith-desktop.org/regolith.key
    state: present
    keyring: /usr/share/keyrings/regolith-archive-keyring.gpg
  become: true

- name: Add the Regolith repository to apt sources
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ regolith_arch }}
      signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg]
      https://regolith-desktop.org/release-{{ regolith_version }}-ubuntu-noble-{{ regolith_arch }}
      noble main
    filename: "regolith"
    state: present
  become: true

- name: Update apt cache again
  apt:
    update_cache: true
  become: true

- name: Install regolith
  apt:
    name:
      - i3
      - picom
      - regolith-desktop
      - regolith-session-flashback
      - regolith-look-lascaille
      - gnome-screenshot
      # - i3lock-fancy
    state: present
  become: true

- name: Remove existing regolith3 directory
  file:
    path: "${HOME}/.config/regolith3"
    state: absent

- name: Install i3-autolayout
  shell: cargo install --root /usr i3-autolayout
  become: true

- name: Copy files
  copy:
    src: "{{playbook_dir}}/../regolith3"
    dest: "${HOME}/.config/"

- name: Make bar scripts executable
  file:
    path: "${HOME}/.config/regolith3/i3xrocks/scripts"
    recurse: true
    state: directory
    mode: "u+x"

- name: Make launch scripts executable
  file:
    path: "{{ item }}"
    mode: "u+x"
  loop:
    - "${HOME}/.config/kitty/launch"
    - "${HOME}/.config/regolith3/picom/init"
