---
- name: Install packages
  homebrew:
    name:
      - python3
      - bash
      - fastfetch
      - tmux
      - neovim
      - fd
      - llvm
      - yq
      - git-lfs
      - eza
      - ncdu
      - bottom
      - cmake
      - unzip
      - thefuck
      - bat
      - wget
      - gnu-tar
      - alacritty
      - fontconfig
      - luarocks
      - axel
      - rust
    state: present

- name: Install cask
  homebrew_cask:
    name:
      - nikitabobko/tap/aerospace
      - alfred
    state: present

- name: Install ripgrep
  include_role:
    name: common/ripgrep

- name: Install lazySQL
  include_role:
    name: common/lazysql
  vars:
    os: Darwin
    arch: arm64

- name: Install lazydocker
  include_role:
    name: common/lazydocker
  vars:
    os: Darwin
    arch: arm64

- name: Install lazygit
  include_role:
    name: common/lazygit
  vars:
    os: Darwin
    arch: arm64

- name: Download and install NVM
  include_role:
    name: common/nvm

- name: Install fzf
  include_role:
    name: common/fzf

- name: Create symlink for python
  shell: >
    rm -f $(dirname $(which python3))/python &&
    ln -s $(which python3) $(dirname $(which python3))/python
  become: true

- name: Create symlink for tmux
  file:
    src: /opt/homebrew/bin/tmux
    dest: /usr/local/bin/tmux
    state: link
  become: true

- name: Install go
  include_role:
    name: common/go
  vars:
    version: 1.23.0
    os: darwin
    arch: arm64

- name: Install oh-my-zsh
  include_role:
    name: common/oh-my-zsh

- name: Remove .tmux
  file:
    path: "${HOME}/.tmux"
    state: absent

- name: tpm
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

- name: Remove .config
  file:
    path: "${HOME}/.config"
    state: absent

- name: Copy font files
  copy:
    src: "../NerdFonts/"
    dest: "/Library/Fonts/"

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "${HOME}/.config/"
  loop:
    - "../fzf"
    - "../nvim"
    - "../shell"
    - "../tmux"
    - "../alacritty"
    - "../fastfetch"
    - "../lazygit"
    - "../lazydocker"
    - "../aerospace"

- name: Add source commands to .zshrc
  blockinfile:
    path: "${HOME}/.zshrc"
    block: |
      source ${HOME}/.config/shell/aliases.zsh
      source ${HOME}/.config/shell/exports.zsh
      source ${HOME}/.config/shell/zsh.zsh
      source ${HOME}/.config/shell/p10k.zsh
      source ${HOME}/.config/shell/colors.zsh
      source ${HOME}/.config/fzf/completion.sh
      source ${HOME}/.config/fzf/keybindings.sh
      export PATH="$PATH:/usr/local/go/bin:$HOME/.local/bin"
      export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
    create: true

- name: Run tmux plugin install script
  command: ${HOME}/.tmux/plugins/tpm/scripts/install_plugins.sh

- name: Remove nvim cache
  file:
    path: "${HOME}/.cache/nvim"
    state: absent

- name: Remove nvim plugins
  file:
    path: "${HOME}/.local/share/nvim"
    state: absent

- name: Remove nvim logs
  file:
    path: "${HOME}/.local/state/nvim"
    state: absent

- name: Set default shell to zsh
  user:
    name: "{{ansible_env.USER}}"
    force: true
    shell: /bin/zsh
  become: true

- name: Run nvim commands
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
  shell: ". ${NVM_DIR}/nvm.sh && nvim --headless +TSUpdateSync +MasonToolsInstallSync +qa"
