---
- name: Install packages
  homebrew:
    name:
      - python3
      - bash
      - fastfetch
      - tmux
      - neovim
      - fd
      - llvm
      - yq
      - git-lfs
      - eza
      - ncdu
      - bottom
      - cmake
      - unzip
      - bat
      - wget
      - gnu-tar
      # - kitty
      - fontconfig
      - luarocks
      - axel
      - rust
      - openjdk@21
      # - alacritty
      # - ghostty
    state: present

- name: Install cask
  homebrew_cask:
    name:
      - nikitabobko/tap/aerospace
      - alfred
    state: present

- name: Install ripgrep
  include_role:
    name: common/shared/ripgrep

# - name: Create symlink for python
#   shell: >
#     rm -f $(dirname $(which python3))/python &&
#     ln -s $(which python3) $(dirname $(which python3))/python
#   become: true

- name: Create symlink for tmux
  file:
    src: /opt/homebrew/bin/tmux
    dest: /usr/local/bin/tmux
    state: link
  become: true

- name: Install go
  include_role:
    name: common/shared/go
  vars:
    version: 1.23.0
    os: darwin
    arch: arm64

    #- name: Install oh-my-zsh
    #  include_role:
    #    name: common/shared/oh-my-zsh

- name: Copy font files
  copy:
    src: "{{playbook_dir}}/../NerdFonts/"
    dest: "/Library/Fonts/"

- name: Remove .config
  file:
    path: "${HOME}/.config"
    state: absent

- name: Create .config
  file:
    state: directory
    path: "${HOME}/.config"

- name: Setup zsh
  include_role:
    name: common/shared/zsh

- name: Download and install fnm
  include_role:
    name: common/shared/fnm

- name: Install lazySQL
  include_role:
    name: common/shared/lazysql
  vars:
    os: Darwin
    arch: arm64

- name: Install lazydocker
  include_role:
    name: common/shared/lazydocker
  vars:
    os: Darwin
    arch: arm64

- name: Install lazyjournal
  include_role:
    name: common/shared/lazyjournal

- name: Install lazygit
  include_role:
    name: common/shared/lazygit
  vars:
    os: Darwin
    arch: arm64

- name: Setup tmux
  include_role:
    name: common/shared/tpm

- name: Setup nvim
  include_role:
    name: common/shared/nvim

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "${HOME}/.config/"
  loop:
    # - "{{playbook_dir}}/../kitty"
    # - "{{playbook_dir}}/../alacritty"
    - "{{playbook_dir}}/../ghostty"
    - "{{playbook_dir}}/../fastfetch"
    - "{{playbook_dir}}/../aerospace"
