---
- name: Install packages
  homebrew:
    name:
      - python3
      - bash
      - fastfetch
      - tmux
      - fd
      - llvm
      - yq
      - git-lfs
      - eza
      - ncdu
      - bottom
      - cmake
      - unzip
      - bat
      - wget
      - gnu-tar
      # - kitty
      - fontconfig
      - luarocks
      - axel
      - rust
      - openjdk@21
      # - alacritty
      - ghostty
    state: present

- name: Install cask
  homebrew_cask:
    name:
      - nikitabobko/tap/aerospace
      - alfred
      - zen
    state: present

- name: Install ripgrep
  include_role:
    name: common/shared/ripgrep

- name: Install zoxide
  include_role:
    name: common/shared/zoxide

- name: Create symlink for tmux
  file:
    src: /opt/homebrew/bin/tmux
    dest: /usr/local/bin/tmux
    state: link
  become: true

- name: Install go
  include_role:
    name: common/shared/go
  vars:
    version: 1.23.0
    os: darwin
    arch: arm64

- name: Copy font files
  copy:
    src: "{{playbook_dir}}/../NerdFonts/"
    dest: "/Library/Fonts/"

- name: Remove .config
  file:
    path: "${HOME}/.config"
    state: absent

- name: Create .config
  file:
    state: directory
    path: "${HOME}/.config"

- name: Setup zsh
  include_role:
    name: common/shared/zsh

- name: Download and install fnm
  include_role:
    name: common/shared/fnm

- name: Install lazySQL
  include_role:
    name: common/shared/lazysql

- name: Install lazydocker
  include_role:
    name: common/shared/lazydocker

- name: Install lazyjournal
  include_role:
    name: common/shared/lazyjournal

- name: Install lazygit
  include_role:
    name: common/shared/lazygit

- name: Setup tmux
  include_role:
    name: common/shared/tpm

- name: Setup nvim
  include_role:
    name: common/shared/nvim
  vars:
    os: macos
    arch: arm64
    version: 0.11.2

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "${HOME}/.config/"
  loop:
    - "{{playbook_dir}}/../ghostty"
    - "{{playbook_dir}}/../fastfetch"
    - "{{playbook_dir}}/../aerospace"
