---
- name: Download the latest release of fastfetch
  get_url:
    url: "https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-{{arch}}.deb"
    dest: "/tmp/fastfetch.deb"

- name: Install fastfetch deb
  apt:
    deb: "/tmp/fastfetch.deb"
  become: true
