---
- name: Install Lazygit
  become: true
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  shell: |
    /usr/local/go/bin/go install github.com/jesseduffield/lazygit@latest

- name: Copy files
  copy:
    src: "{{playbook_dir}}/../lazygit"
    dest: "${HOME}/.config/"
