---
- name: Download LazyGit tarball
  get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/download/v{{ version }}/lazygit_{{ version }}_{{os}}_{{ arch }}.tar.gz"
    dest: "/tmp/lazygit.tar.gz"

- name: Extract LazyGit binary
  unarchive:
    src: "/tmp/lazygit.tar.gz"
    dest: "/tmp/"
    creates: "/tmp/lazygit"
    remote_src: true
  when: lazygit_version.stdout is defined

- name: Install LazyGit
  command: install /tmp/lazygit /usr/local/bin
  become: true
  when: lazygit_version.stdout is defined

- name: Copy files
  copy:
    src: "{{playbook_dir}}/../lazygit"
    dest: "${HOME}/.config/"
