vim.keymap.set("n", "<leader>g", ":vertical Git | vertical resize 40<CR>")
vim.keymap.set("n", "<leader>gco", ':Git commit -m ""<Left>')
vim.keymap.set("n", "<leader>gg", ":Git pull --rebase")
vim.keymap.set("n", "<leader>gp", ":Git push -u origin ")
vim.keymap.set("n", "<leader>gm", ":Git merge ")
vim.keymap.set("n", "<leader>gl", ":Git log<CR>")
vim.keymap.set("n", "<leader>gt", ":GV<CR>")
vim.keymap.set("n", "<leader>ga", ":Gwrite<CR>")
vim.keymap.set("n", "<leader>g-", ":Gread<CR>")
vim.keymap.set("n", "<leader>gb", ":Git branch ")
vim.keymap.set("n", "<leader>gch", ":Git checkout ")
vim.keymap.set("n", "<leader>gs", ":Git status<CR>")
