vim.keymap.set("n", "<leader>g", ":vertical Git | vertical resize 60<CR>")
vim.keymap.set("n", "<leader>gco", ':Git commit -m ""<Left>')
vim.keymap.set("n", "<leader>gg", ":Git pull --rebase")
vim.keymap.set("n", "<leader>gp", ":Git push -u origin ")
vim.keymap.set("n", "<leader>gm", ":Git merge ")
vim.keymap.set("n", "<leader>gL", ":vertical Git log | vertical resize 100<CR>")
vim.keymap.set("n", "<leader>gt", ":GV<CR>")
vim.keymap.set("n", "<leader>ga", ":Gwrite<CR>")
vim.keymap.set("n", "<leader>g-", ":Gread<CR>")
vim.keymap.set("n", "<leader>gB", ":Git branch ")
vim.keymap.set("n", "<leader>gch", ":Git checkout ")
vim.keymap.set("n", "<leader>gb", ":Telescope git_branches<CR>")
vim.keymap.set("n", "<leader>gs", ":Telescope git_stash<CR>")
vim.keymap.set("n", "<leader>gsa", ":Git stash<CR>")
vim.keymap.set("n", "<leader>gsp", ":Git stash pop<CR>")
vim.keymap.set("n", "<leader>gf", ":Telescope git_files<CR>")
vim.keymap.set("n", "<leader>gl", ":Telescope git_commits<CR>")

