---
- name: Install zoxide to temporary directory
  shell: cargo install --root /tmp/zoxide --version 0.9.9 zoxide
  become: false
  environment:
    PATH: "{{ ansible_facts['env'].HOME }}/.cargo/bin:{{ ansible_facts['env'].PATH }}"
    HOME: "{{ ansible_facts['env'].HOME }}"
  args:
    creates: "/tmp/zoxide/bin/zoxide"

- name: Copy zoxide binary to /usr/local/bin
  copy:
    src: "/tmp/zoxide/bin/zoxide"
    dest: "/usr/local/bin/zoxide"
    mode: "0755"
  become: true
