require("harpoon"):setup()

vim.keymap.set("n", "<leader>ha", function() require("harpoon"):list():add() end, { desc = "harpoon add file" })
vim.keymap.set("n", "<leader>hs", function()
    local harpoon = require("harpoon")
    harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "harpoon quick menu" })
vim.keymap.set("n", "<leader>h1", function() require("harpoon"):list():select(1) end, { desc = "harpoon to file 1" })
vim.keymap.set("n", "<leader>h2", function() require("harpoon"):list():select(2) end, { desc = "harpoon to file 2" })
vim.keymap.set("n", "<leader>h3", function() require("harpoon"):list():select(3) end, { desc = "harpoon to file 3" })
vim.keymap.set("n", "<leader>h4", function() require("harpoon"):list():select(4) end, { desc = "harpoon to file 4" })
vim.keymap.set("n", "<leader>h5", function() require("harpoon"):list():select(5) end, { desc = "harpoon to file 5" })
vim.keymap.set("n", "<leader>h6", function() require("harpoon"):list():select(6) end, { desc = "harpoon to file 6" })
vim.keymap.set("n", "<leader>h7", function() require("harpoon"):list():select(7) end, { desc = "harpoon to file 7" })
vim.keymap.set("n", "<leader>h8", function() require("harpoon"):list():select(8) end, { desc = "harpoon to file 8" })
vim.keymap.set("n", "<leader>h9", function() require("harpoon"):list():select(9) end, { desc = "harpoon to file 9" })
