---
- hosts: localhost
  gather_facts: true
  roles:
    - role: macos
      when: ansible_os_family == "Darwin"
    - role: ubuntu
      when: ansible_os_family == "Debian"

  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US:en
    LC_ALL: en_US.UTF-8
