---
- name: Get the latest LazyDocker version
  shell: >
    curl -s
    "https://api.github.com/repos/jesseduffield/lazydocker/releases/latest" |
    rg -Po '"tag_name": "v\K[^"]*'
  register: lazydocker_version

- name: Download LazyDocker tarball
  get_url:
    url: "https://github.com/jesseduffield/lazydocker/releases/latest/download/lazydocker_{{ lazydocker_version.stdout }}_{{os}}_{{ arch }}.tar.gz"
    dest: "/tmp/lazydocker.tar.gz"
  when: lazydocker_version.stdout is defined

- name: Extract LazyDocker binary
  unarchive:
    src: "/tmp/lazydocker.tar.gz"
    dest: "/tmp/"
    creates: "/tmp/lazydocker"
    remote_src: true
  when: lazydocker_version.stdout is defined

- name: Install LazyDocker
  command: install /tmp/lazydocker /usr/local/bin
  become: true
  when: lazydocker_version.stdout is defined

