---
- name: Download nvim
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v{{ version }}/nvim-{{os}}-{{arch}}.tar.gz"
    dest: "/tmp/nvim.tar.gz"
    mode: "0644"

- name: Extract nvim
  unarchive:
    src: "/tmp/nvim.tar.gz"
    dest: "/usr/local"
    remote_src: true
    extra_opts: [--strip-components=1]
  become: true

- name: Copy files
  copy:
    src: "{{playbook_dir}}/../nvim"
    dest: "${HOME}/.config/"

- name: Remove nvim cache
  file:
    path: "${HOME}/.cache/nvim"
    state: absent

- name: Copy files
  copy:
    src: "{{playbook_dir}}/../mini"
    dest: "${HOME}/.config/"

- name: Remove nvim cache
  file:
    path: "${HOME}/.cache/mini"
    state: absent

- name: Remove nvim plugins
  file:
    path: "${HOME}/.local/share/nvim"
    state: absent

- name: Remove nvim logs
  file:
    path: "${HOME}/.local/state/nvim"
    state: absent

- name: Install ticktoken-core
  shell: "luarocks install --lua-version 5.1 tiktoken_core"
  environment:
    PATH: "${HOME}/.cargo/bin:{{ ansible_env.PATH }}"
  become: true

- name: Install pynvim on macOS
  when: ansible_os_family == "Darwin"
  shell: |
    /opt/homebrew/bin/pip3.12 install --break-system-packages pynvim

- name: Install pynvim on Linux
  when: ansible_os_family != "Darwin"
  shell: |
    /usr/bin/python3 -m pip install --break-system-packages pynvim

- name: Run nvim commands
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
    FNM_DIR: "{{ ansible_env.HOME }}/.fnm"
  shell: 'eval "$($FNM_DIR/fnm env)" && nvim --headless +TSUpdateSync +MasonToolsInstallSync +qa'
