---
- name: Copy files
  copy:
    src: "{{playbook_dir}}/../nvim"
    dest: "${HOME}/.config/"

- name: Remove nvim cache
  file:
    path: "${HOME}/.cache/nvim"
    state: absent

- name: Copy files
  copy:
    src: "{{playbook_dir}}/../mini"
    dest: "${HOME}/.config/"

- name: Remove nvim cache
  file:
    path: "${HOME}/.cache/mini"
    state: absent

- name: Remove nvim plugins
  file:
    path: "${HOME}/.local/share/nvim"
    state: absent

- name: Remove nvim logs
  file:
    path: "${HOME}/.local/state/nvim"
    state: absent

- name: Install ticktoken-core
  shell: "sudo luarocks install --lua-version 5.1 tiktoken_core"
  environment:
    PATH: "${HOME}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Install pynvim on macOS
  when: ansible_os_family == "Darwin"
  shell: |
    /opt/homebrew/bin/pip3.12 install --break-system-packages pynvim

- name: Install pynvim on Linux
  when: ansible_os_family != "Darwin"
  shell: |
    /usr/bin/python3 -m pip install --break-system-packages pynvim

- name: Run nvim commands
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
  shell: ". ${NVM_DIR}/nvm.sh && nvim --headless +TSUpdateSync +MasonToolsInstallSync +qa"
